CREATE TABLE users (
    no INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	id VARCHAR(64) NOT NULL UNIQUE,
	username VARCHAR(100) NOT NULL,
	password VARCHAR(100) NOT NULL,
	name VARCHAR(100) NOT NULL,
	email VARCHAR(100) NULL,
	birth VARCHAR(100) NULL,
	tel   VARCHAR(100) NULL,
	created_at TIMESTAMP NOT NULL DEFAULT now(),
	updated_at TIMESTAMP NOT NULL DEFAULT now()
);